### ISSUE TITLE
get_vecs.py: NameError

### ISSUE THREAD

**Issue by selfmeister** [USC-CSSL/DDR#2]
line 276    should probably be            `print "\nFinished calculating aggregate document representations", "\nNumber of NA:", n_na`.
for 

> /Users/me/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ddr/get_vecs.pyc in doc_vecs_from_txt(input_path, output_path, num_features, model, model_word_set, delimiter, filter_out)
>     274                         n_na += 1
>     275                         pass
> --> 276                 print "\nFinished calculating aggregate document representations", "\nNumber of NA:", na_na
>     277 
>     278 
> 
> NameError: global name 'na_na' is not defined

**Comment by jgarten** [comment]
Fixed. Sorry for the delay on this.
