### ISSUE TITLE
Problem loading model

### ISSUE THREAD

**Issue by Sam8246** [USC-CSSL/DDR#3]
Hello,

I am running python 2.7 and have all the necessary dependencies for using the DDR module. As stated in the tutorial, I went and downloaded the Google News word vectors. When I attempt to load the vector model I get an error saying that it can't find the file (see code below). This confuses me because to the best of my knowledge I have correctly specified the file path, but the model still isn't being found. Do you have any suggestions for how I can help the DDR module access the model? 

import ddr
model, num_features, index2word_set = ddr.load_model(model_path = 'C:\\NLP\\GoogleNews-vectors-negative300.bin')
IOError: [Errno 2] No such file or directory: 'C:\\NLP\\GoogleNews-vectors-negative300.bin'

**Comment by jgartensc** [comment]
I'll take a look at this. Give me a day or so and I should have an update for you (looks like you're running windows, so I'll need to grab something running that to test on).

**Comment by jgarten** [comment]
The issue is with the windows path backslashes (treated as an escape character here). You can either switch your path to:
'C:\\NLP\\Google...'
or
'C:/NLP/Google...'

Here's a post which covers this:
https://stackoverflow.com/questions/2953834/windows-path-in-python

**Comment by Sam8246** [comment]
Thanks for your help. I re-specified the path as you suggested and it did not work. At first I thought I had just entered the path incorrectly, but I don't think that's the issue. In fact, the stackoverflow page you linked to is one of the resources I sought before posting. Besides re-specifying the path, what other approaches might I take for debugging my code?

**Comment by jgarten** [comment]
I setup DDR on windows and I'm not able to reproduce what you're describing. Here's what I ran in python (after installing everything):
> import ddr
> model_path = "C:/Users/struct/Documents/ddr_test/GoogleNews-vectors-negative300.bin"
> model, num, word_set = ddr.load_model(model_path)

This works fine. When I change it to an incorrect path it gives the error you describe. Could you send the exact commands you're using with the corrected path?

**Comment by Sam8246** [comment]
import ddr
model_path = "C:/NLP/GoogleNews-vectors-negative300.bin"
model, num, word_set = ddr.load_model(model_path)

This code does not work for me, I get a no such file or directory error. When I import ddr I get this warning though:

Warning (from warnings module):
  File "C:\Users\v-mahug\lib\site-packages\gensim\utils.py", line 1167
    warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
UserWarning: detected Windows; aliasing chunkize to chunkize_serial
2018-03-02 20:26:14,352 : INFO : 'pattern' package found; tag filters are available for English

I do not know what this warning means. Might this be part of the issue?
