### ISSUE TITLE
Unable to install package using r-reticulate

### ISSUE THREAD

**Issue by PsychAnon** [USC-CSSL/DDR#6]
I am trying to use the DDR package in R because I do not know Python. To do so, I am using the reticulate package in R that allows you to install and use Python package in your R environment. I have used reticulate::py_install() to install various packages (e.g., numpy, pandas, etc.), but it is unable to find and download the DDR package. How can I install and use the DDR package in R with reticulate?

**Comment by mdehghanim** [comment]
Unfortunately, we currently do not provide support for reticulate. We might provide this functionality in the near future.
